### ISSUE TITLE
TOC position

### ISSUE THREAD

**Issue by f-nobre** [ipari/dokuwiki-template-white#13]
Hi, I changed my wiki to this template. Congratulations, it's a really good template.

The only thing bothering me is the TOC position. My content became ugly because I use a lot of columns in my content and the TOC on the left side breaks the content pushing it down.

Since you already have a TOC configuration option, could you please add the option to leave in the default top-right as usual? I tried the [dokuwiki] and [wikimedia] options but no luck, both put the TOC on the left. Another nice config option would be to have the TOC collapsed by default

Regards

**Comment by ipari** [comment]
Sorry for too late response.
I do not prefer but I'll support that layout if more users want.
Or try edit below .less files.

``` less
// content.less
#dw__toc {
    float: inherit;  // remove or comment this
    margin: 0 0 1.4em 1em;  // add margin to left
}
```

```less
// mobile.less
#dw__toc {
    float: inherit;  // add this line.
}
```
